# Generated by Django 5.2.3 on 2026-02-08 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ga4_measurement_id',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
