# Generated by Django 5.2.3 on 2026-02-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_testimonial_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='quote_el',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='quote_en',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True, default=''),
        ),
    ]
