# Generated by Django 5.2.11 on 2026-10-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutcontent_clientlogo_contactcontent_footercontent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_enabled',
            field=models.BooleanField(default=True, verbose_name='AdSense enabled'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='adsense_publisher_id',
            field=models.CharField(blank=True, default='ca-pub-7179497516124377', help_text='From AdSense: Account > Settings > Account information, e.g. ca-pub-1234567890123456. Also used for /ads.txt.', max_length=40, verbose_name='AdSense publisher ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_el',
            field=models.TextField(default='Επαγγελματική ψηφιακή μάρκετινγκ αγορά που προσφέρει σχεδιασμό ιστοσελίδων, ανάπτυξη και ψηφιακές λύσεις μάρκετινγκ.', max_length=320, verbose_name='Meta description (EL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description_en',
            field=models.TextField(default='Professional digital marketing agency offering web design, development, and digital marketing solutions.', max_length=320, verbose_name='Meta description (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_keywords',
            field=models.CharField(blank=True, default='digital marketing, web design, web development, SEO, branding, social media marketing', max_length=255, verbose_name='Meta keywords'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_el',
            field=models.CharField(default='InaDigiWay - Digital Marketing Agency', max_length=120, verbose_name='Page title (EL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_title_en',
            field=models.CharField(default='InaDigiWay - Digital Marketing Agency', max_length=120, verbose_name='Page title (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='og_image',
            field=models.ImageField(blank=True, help_text='Recommended 1200x630. Leave empty to use the default image.', null=True, upload_to='seo/', verbose_name='Share image (Facebook, LinkedIn, X)'),
        ),
    ]
