# Generated by Django 5.2.11 on 2026-10-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_sitesettings_seo_adsense'),
    ]

    operations = [
        migrations.AddField(
            model_name='footercontent',
            name='google_business_url',
            field=models.URLField(blank=True, default='https://maps.google.com/?cid=4682699893593634570', help_text='Google Maps link of the business profile (footer icon + structured data). Leave empty to hide.', verbose_name='Google Business Profile URL'),
        ),
    ]
